# Generated by Django 4.2.30 on 2026-05-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PRNProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('form', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('route_of_administration', models.CharField(max_length=100)),
                ('dose_and_frequency', models.TextField()),
                ('min_time_interval', models.CharField(max_length=100)),
                ('max_dose_24h', models.CharField(max_length=100)),
                ('capacity_statement', models.TextField()),
                ('reason_for_administration', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('gp_persistent_need', models.BooleanField(default=False)),
                ('gp_never_requesting', models.BooleanField(default=False)),
                ('gp_requesting_too_often', models.BooleanField(default=False)),
                ('gp_side_effects', models.BooleanField(default=False)),
                ('gp_other', models.CharField(blank=True, max_length=200)),
                ('prepared_by_name', models.CharField(blank=True, max_length=200)),
                ('prepared_by_designation', models.CharField(blank=True, max_length=100)),
                ('prepared_by_date', models.DateField(blank=True, null=True)),
                ('approved_by_name', models.CharField(blank=True, max_length=200)),
                ('approved_by_designation', models.CharField(blank=True, max_length=100)),
                ('approved_by_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=200)),
                ('reviewed_by_designation', models.CharField(blank=True, max_length=100)),
                ('reviewed_by_date', models.DateField(blank=True, null=True)),
                ('checked_by_name', models.CharField(blank=True, max_length=200)),
                ('checked_by_designation', models.CharField(blank=True, max_length=100)),
                ('checked_by_date', models.DateField(blank=True, null=True)),
                ('new_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='core.resident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
