# Generated by Django 4.2.30 on 2026-05-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prnprotocol",
            name="medication_instruction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resident",
            name="mental_capacity",
            field=models.TextField(blank=True),
        ),
    ]
