# Generated by Django 4.2.30 on 2026-05-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_prnprotocol_medication_instruction_and_more"),
        ("core", "0002_resident_mental_capacity_prnprotocol_medication_instruction"),
    ]

    operations = []
