# Generated by Django 4.2.30 on 2026-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20260513_0937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prnprotocol",
            name="medication_instruction",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="resident",
            name="mental_capacity",
            field=models.TextField(blank=True, default=""),
        ),
    ]
