# Generated by Django 4.2.30 on 2026-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_resident_medical_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="care_plan_reviewed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resident",
            name="gp_contact",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="resident",
            name="gp_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="resident",
            name="gp_surgery",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="resident",
            name="next_of_kin",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="resident",
            name="next_of_kin_contact",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="resident",
            name="nhs_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="resident",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="resident_photos/"
            ),
        ),
    ]
