# Generated by Django 4.2.30 on 2026-05-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_resident_care_plan_reviewed_resident_gp_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='administration_preferences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='care_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='legal_safeguarding_information',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='mar_front_page_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='medication_alerts',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='monitoring_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resident',
            name='pharmacy_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='pharmacy_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resident',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('reviewed', 'Reviewed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('review', 'Review'), ('export_pdf', 'Export PDF'), ('export_docx', 'Export DOCX'), ('print', 'Print'), ('ai_assist', 'AI assist')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('entity_label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.resident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
