# Generated by Django 4.2.30 on 2026-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_resident_administration_preferences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="residential_or_nursing",
            field=models.CharField(
                choices=[("residential", "Residential"), ("nursing", "Nursing")],
                default="residential",
                max_length=20,
            ),
        ),
    ]
